version: '3.9'
services:
  database:
    image: mysql:8.0.21
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_USER=${OPTSICOM_DB_USER}
      - MYSQL_ROOT_PASSWORD=${OPTSICOM_DB_SECRET}
      - MYSQL_DATABASE=${OPTSICOM_DB_SCHEMA}
    volumes:
      - ${OPTSICOM_DB_DATA_PATH}:/var/lib/mysql

  optsicom-web:
    image: codeurjc/optsicom-web:latest
    ports:
      - 5000:5000
    depends_on:
      - database
    environment:
      # Configure database
      - OPTSICOM_DB_MODE=${OPTSICOM_DB_MODE}
      - OPTSICOM_DB_HOST=database
      - OPTSICOM_DB_PORT=3306
      - OPTSICOM_DB_SCHEMA=${OPTSICOM_DB_SCHEMA}
      - OPTSICOM_DB_USER=${OPTSICOM_DB_USER}
      - OPTSICOM_DB_SECRET=${OPTSICOM_DB_SECRET}

      # Configure login for optsicom web
      - OPTSICOM_API_USER=${OPTSICOM_API_USER}
      - OPTSICOM_API_SECRET=${OPTSICOM_API_SECRET}

      # Configure Java params
      - JAVA_OPTIONS=${JAVA_OPTIONS:-}