name: Optsicom Web Image

on:
  push:
    branches:
      - master
    paths:
      - 'es.optsicom.lib.web/**'

jobs:
  create_image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: |
          cd es.optsicom.lib.web/docker/optsicom-web
          ./create_image.sh
      - name: Tags
        run: |
          docker tag codeurjc/optsicom-web codeurjc/optsicom-web:master
          docker tag codeurjc/optsicom-web codeurjc/optsicom-web:latest
      - name: Docker push
        run: |
          docker push codeurjc/optsicom-web:master
          docker push codeurjc/optsicom-web:latest
