name: Testing Actions
  
on:
  push:
    branches:
      - test-actions

jobs:
  test:
    runs-on: ubuntu-18.04
    container:
      image: codeurjc/optsicom-builder

    steps:
      - uses: actions/checkout@v2  
      - name: Compile Optsicom Web
        run: |
          cd adm-scripts
          ./compile_optsicom_web.sh install_dependencies
      - name: Create docker image
        run: |
          cd es.optsicom.lib.web/docker/optsicom-web
          ./create_image.sh
